# Namespace: kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1
  namespace: kafka
  labels:
    app: kafka-broker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      hostname: kafka-broker-1
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.3.2
        ports:
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-1:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://kafka-broker-1:9092"
        - name: KAFKA_BROKER_ID
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  namespace: kafka
spec:
  ports:
  - name: external
    port: 9092
    targetPort: 9092
  - name: internal
    port: 29092
    targetPort: 29092
  selector:
    app: kafka-broker-1
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-2
  namespace: kafka
  labels:
    app: kafka-broker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-2
  template:
    metadata:
      labels:
        app: kafka-broker-2
    spec:
      hostname: kafka-broker-2
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.3.2
        ports:
        - containerPort: 9093
        - containerPort: 29093
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-1:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-broker-2:29093,PLAINTEXT_HOST://kafka-broker-2:9093"
        - name: KAFKA_BROKER_ID
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2
  namespace: kafka
spec:
  ports:
  - name: external
    port: 9093
    targetPort: 9093
  - name: internal
    port: 29093
    targetPort: 29093
  selector:
    app: kafka-broker-2
  type: ClusterIP




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-3
  namespace: kafka
  labels:
    app: kafka-broker-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-3
  template:
    metadata:
      labels:
        app: kafka-broker-3
    spec:
      hostname: kafka-broker-3
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.3.2
        ports:
        - containerPort: 9094
        - containerPort: 29094
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-1:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-broker-3:29094,PLAINTEXT_HOST://kafka-broker-3:9094"
        - name: KAFKA_BROKER_ID
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3
  namespace: kafka
spec:
  ports:
  - name: external
    port: 9094
    targetPort: 9094
  - name: internal
    port: 29094
    targetPort: 29094
  selector:
    app: kafka-broker-3
  type: ClusterIP




# kubectl delete statefulset kafka -n kafka
# kubectl delete service kafka-hs kafka-cs -n kafka
# kubectl delete pvc datadir-kafka-0 datadir-kafka-1 datadir-kafka-2 -n kafka


## kubectl apply -f 3-kafka.yaml
## kubectl get pods -n kafka -l app=kafka --watch
## kubectl get svc -n kafka -l app=kafka --watch

