# grafana-values.yaml

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.test
  pathType: Prefix
  path: /

persistence:
  enabled: true

adminPassword: "minhasenhacorreta"
