
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-kafka
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: init-kafka
        image: confluentinc/cp-kafka:7.3.2
        command:
        - /bin/sh
        - -c
        - |
          kafka-topics --bootstrap-server kafka-broker-1:29092 --list && \
          kafka-topics --bootstrap-server kafka-broker-1:29092 --create --if-not-exists --topic test-event --replication-factor 3 --partitions 3 && \
          kafka-topics --bootstrap-server kafka-broker-1:29092 --list
      restartPolicy: OnFailure


