# runner-permissions.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner-pods-lister
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-binding
subjects:
- kind: ServiceAccount
  name: default # O nome da ServiceAccount
  namespace: github-runners
roleRef:
  kind: ClusterRole
  name: github-runner-pods-lister
  apiGroup: rbac.authorization.k8s.io