# gitlab-runner/taskfile.yml

# https://medium.com/simform-engineering/how-to-setup-self-hosted-github-action-runner-on-kubernetes-c8825ccbb63c
# https://dev.to/viradiaharsh/hosting-self-hosted-github-runners-on-kubernetes-o2d

# create github APP: 
# https://github.com/settings/apps
# https://github.com/settings/tokens

version: '3'

vars:
  XPTO: v0.23.0
  CM_NAMESPACE: cert-manager
  CM_VERSION: v1.13.0

  GITHUB_APP_ID: 
  GITHUB_APP_INSTALLATION_ID: 
  GITHUB_PRIVATE_KEY_FILE: ./poc-learn-kind-k8s-self-runner.2025-09-01.private-key.pem

tasks:
  default:
    desc: "Lists all available tasks."
    cmds:
      - task --list-all

  CertManager:install:
    desc: "Install CertManager"
    cmds:
      - helm repo add jetstack https://charts.jetstack.io --force-update
      - |
        helm install cert-manager jetstack/cert-manager --namespace {{.CM_NAMESPACE}} --create-namespace  --version {{.CM_VERSION}} --set installCRDs=true

  CertManager:crds-install:
    desc: "Install crds CertManager"
    cmds:
      - kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.crds.yaml

  CertManager:status:
    desc: "Check CertManager status"
    cmds:
      - kubectl get pods --namespace {{.CM_NAMESPACE}}


  ARCGitHub:namespace:
    desc: "Create actions namespace"
    cmds:
      - kubectl create namespace actions
    when:
      not:
        - kubectl get namespace actions
    status:
      - kubectl get namespace actions

  ARCGitHub:CreateSecret:
    desc: "Create docker-registry secret in kubernetes"
    deps: [ARCGitHub:namespace]
    cmds:
      - |
        kubectl create secret generic controller-manager -n actions \
          --from-literal=github_app_id={{.GITHUB_APP_ID}} \
          --from-literal=github_app_installation_id={{.GITHUB_APP_INSTALLATION_ID}} \
          --from-literal=github_app_private_key={{.GITHUB_PRIVATE_KEY_FILE}}

  ARCGitHub:install:
    desc: "Install Actions Runner Controller"
    cmds:
      - helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
      - helm repo update
      - helm install actions-runner-controller   actions-runner-controller/actions-runner-controller   --namespace actions-runner-system   --create-namespace
      #- |
      #  helm install actions-runner-controller actions-runner-controller/actions-runner-controller \
      #    --namespace actions \
      #    --version 0.23.7 \
      #    --create-namespace \
      #    --set syncPeriod=1m


