# argocd-values.yaml
config:
  params:
    server.insecure: true

global:
  domain: argocd.test

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.test
    extraHosts:
      - name: argocd.test
        path: / 
    https: false
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  extraArgs:
    - --insecure

controller:
  persistence:
    enabled: false

redis-ha:
  enabled: false