version: '3'

vars:
  GRAFANA_RELEASE: my-grafana
  GRAFANA_HOSTNAME: grafana.test

tasks:
  default:
    desc: "Lists all available tasks."
    cmds:
      - task --list-all


  grafana:install:
    desc: "Installs Grafana from the official chart."
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts
      - helm repo update
      - |
        helm install {{.GRAFANA_RELEASE}} grafana/grafana \
          --set persistence.enabled=true \
          --set persistence.size=10Gi \
          --set service.port=80 \
          --set ingress.enabled=true \
          --set ingress.annotations."kubernetes\.io/ingress\.class"="nginx" \
          --set ingress.ingressClassName=nginx \
          --set ingress.hosts[0]={{.GRAFANA_HOSTNAME}} \
          --set ingress.tls[0].hosts[0]={{.GRAFANA_HOSTNAME}} \
          --set ingress.tls[0].secretName=grafana-tls

  grafana:uninstall:
    desc: "Uninstalls the Grafana release."
    cmds:
      - helm uninstall {{.GRAFANA_RELEASE}}

  grafana:show-access:
    desc: "Shows Grafana password and starts port-forwarding."
    cmds:
      - |
        echo "--------------------------------------------------"
        echo "Grafana Access for release '{{.GRAFANA_RELEASE}}'"
        echo "URL: http://{{.GRAFANA_HOSTNAME}}:3000"
        echo "User: admin"
        echo -e "Password: "
        kubectl get secret {{.GRAFANA_RELEASE}} -o jsonpath="{.data.admin-password}" | base64 --decode
        echo -e "\n--------------------------------------------------"
        echo "Starting port-forward. Press Ctrl+C to stop."
        # kubectl port-forward svc/{{.GRAFANA_RELEASE}} 3000:80
