# .github/workflows/validate-manifests.yml
name: Validate K8s Manifests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '15 3 * * 1'
  workflow_dispatch:

jobs:
  validate:
    runs-on: self-hosted

    container:
      image: ubuntu:22.04
      options: --privileged

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Taskfile
        run: |
          # Checa se o 'task' já existe, senão, instala
          if ! command -v task &> /dev/null; then
            echo "Taskfile not found. Installing..."
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          else
            echo "Taskfile is already installed."
          fi

      - name: 3. Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.2'

      - name: 4. Run Validation Task
        run: task ci:validate 
