# .github/workflows/validate-manifests.yml
name: Validate K8s Manifests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '15 3 * * 1'
  workflow_dispatch:

jobs:
  validate:
    runs-on: self-hosted

    container:
      image: ubuntu:22.04

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Install Kubeval
        run: |
          apt update && apt install -y wget tar curl
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          mv kubeval /usr/local/bin

      - name: 3. Validate Kubernetes Manifests
        run: find ./apps -type f \( -name "*.yaml" -o -name "*.yml" \) -not -name "taskfile.yml" -print0 | xargs -0 kubeval --ignore-missing-schemas