# .github/workflows/validate-manifests.yml
name: Validate K8s Manifests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '15 3 * * 1'
  workflow_dispatch:

jobs:
  validate:
    runs-on: self-hosted

    container:
      image: ubuntu:22.04

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.2'

      - name: 3. Install Task and Run Validation
        run: |
          # Instala o Taskfile se não existir
          if ! command -v task &> /dev/null; then
            echo "Taskfile not found. Installing..."
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          else
            echo "Taskfile is already installed."
          fi

          # Executa a validação
          echo "Running validation..."
          task ci:validate