# .github/workflows/validate-manifests.yml
name: Validate K8s Manifests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '15 3 * * 1'
  workflow_dispatch:

jobs:
  validate:
    runs-on: self-hosted

    container:
      image: ubuntu:22.04

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Install basic dependencies
        run: |
          - bash devops/bootstrap/install_basic_depencencies.sh

      - name: 3. Validate Kubernetes Manifests
        run: |
          - task -d ./CICD/ validate:manifests:kubectl
          - task -d ./CICD/ validate:manifests:kubeval
          - task -d ./CICD/ validate:helmfiles

